name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive 
    - name: configure
      run: ./configure.sh
    - name: cmake
      run: cd build && cmake ..
    - name: make
      run: make -j4
