name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SDL
      run: sudo apt-get install -y libsdl2-dev
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive 
    - name: configure
      run: ./deps.sh
    - name: make
      run: make
