name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout spdlog
      uses: actions/checkout@v2
      with:
        repository: https://github.com/gabime/spdlog
        path: vendor
    - name: configure
      run: ./deps.sh
    - name: make
      run: make
